In [1]:
import numpy as np
my_arr=np.arange(1000)

In [2]:
my_list=list(range(1000))

In [4]:
data=np.random.randn(2,3)
data

array([[ 1.46768843,  0.8818424 ,  1.46177042],
       [ 0.45461716, -0.23908718, -0.76324006]])

In [5]:
data*2

array([[ 2.93537686,  1.7636848 ,  2.92354085],
       [ 0.90923432, -0.47817436, -1.52648012]])

In [6]:
data+data

array([[ 2.93537686,  1.7636848 ,  2.92354085],
       [ 0.90923432, -0.47817436, -1.52648012]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [10]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.shape

(2, 4)

In [15]:
arr2.ndim

2

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((4,3,2))

array([[[3.88900327e-312, 7.90505033e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.15710835e-306, 1.15998412e-028]],

       [[2.44171989e+232, 8.00801729e+159],
        [9.45007090e-076, 6.98345624e-077],
        [6.98345624e-077, 6.98345624e-077]],

       [[6.98345624e-077, 1.03080217e+136],
        [6.01347002e-154, 7.06652016e-096],
        [7.06652016e-096, 7.06652016e-096]],

       [[7.06652016e-096, 7.18988929e+140],
        [3.77780862e+180, 1.15998412e-028],
        [6.48224638e+170, 3.67145870e+228]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr1=np.array([1,2,3],dtype=np.float)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2=np.array([1,2,3])
arr2.dtype

dtype('int32')

In [43]:
arr=np.array([1.1,2.1,3.2,4.5])
arr

array([1.1, 2.1, 3.2, 4.5])

In [44]:
arr.astype(np.int)

array([1, 2, 3, 4])

In [48]:
arr1= np.array(['1.2','1.4','3.2'],dtype=np.string_)
arr1

array([b'1.2', b'1.4', b'3.2'], dtype='|S3')

In [56]:
arr1.astype(float)

array([1.2, 1.4, 3.2])

In [55]:
arr1= np.array(['1.2','1.4','3.2'],dtype=np.string_)
arr1.astype(arr.dtype)

array([b'1.2', b'1.4', b'3.2'], dtype='|S3')

In [59]:
arr*arr

array([ 1.21,  4.41, 10.24, 20.25])

In [60]:
arr-arr

array([0., 0., 0., 0.])

In [61]:
1/arr

array([0.90909091, 0.47619048, 0.3125    , 0.22222222])

In [62]:
arr**0.5

array([1.04880885, 1.44913767, 1.78885438, 2.12132034])

In [63]:
arr[2]

3.2

In [64]:
arr[:2]

array([1.1, 2.1])

In [65]:
arr[0]=1

In [66]:
arr

array([1. , 2.1, 3.2, 4.5])

In [68]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1]

array([4, 5, 6])

In [69]:
arr2d[1][1]

5

In [70]:
arr2d[1,1]

5

In [72]:
old=arr2d[2].copy()

In [73]:
arr2d[2]=0
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [76]:
arr2d[2]=old
arr2d

array([[7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
 arr2d[:2,1:]

array([[8, 9],
       [5, 6]])

In [25]:
names=np.array(['bob','alice','joe','bob','joe'])

In [86]:
data=np.random.randn(5,4)
data

array([[-0.09148231, -0.6779727 ,  0.76840062,  0.18856675],
       [ 0.99320451, -1.09057813, -1.02472128, -0.79236075],
       [-2.71046922, -0.31773126,  0.26263777, -0.25230624],
       [ 1.5295812 ,  1.6388994 ,  0.47896622,  1.12699866],
       [-1.81241577, -0.71027243,  0.04963043, -0.55698739]])

In [85]:
names=='bob'

array([ True, False, False,  True, False])

In [87]:
data[names=='bob']

array([[-0.09148231, -0.6779727 ,  0.76840062,  0.18856675],
       [ 1.5295812 ,  1.6388994 ,  0.47896622,  1.12699866]])

In [94]:
data[names=='bob',2:]

array([[0.76840062, 0.18856675],
       [0.47896622, 1.12699866]])

In [96]:
data[names=='bob'][:1]

array([[-0.09148231, -0.6779727 ,  0.76840062,  0.18856675]])

In [97]:
data[names=='bob',2]

array([0.76840062, 0.47896622])

In [105]:
data[~(names!='bob')]

array([[-0.09148231, -0.6779727 ,  0.76840062,  0.18856675],
       [ 1.5295812 ,  1.6388994 ,  0.47896622,  1.12699866]])

In [107]:
data[data<0]=0

In [108]:
data

array([[0.        , 0.        , 0.76840062, 0.18856675],
       [0.99320451, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.26263777, 0.        ],
       [1.5295812 , 1.6388994 , 0.47896622, 1.12699866],
       [0.        , 0.        , 0.04963043, 0.        ]])

In [110]:
data[names!='bob']=1

In [111]:
data

array([[0.        , 0.        , 0.76840062, 0.18856675],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.5295812 , 1.6388994 , 0.47896622, 1.12699866],
       [1.        , 1.        , 1.        , 1.        ]])

In [113]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [115]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [117]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [119]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [120]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [121]:
np.dot(arr.T,arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [123]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436]])

In [124]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13]])

In [125]:
x=np.random.randn(10)
y=np.random.randn(10)

In [126]:
x

array([ 2.34683007,  0.45577208, -2.31249293, -0.13223669,  1.5466289 ,
       -0.26236228, -0.90827677, -0.36484072, -0.30743934,  1.14949153])

In [127]:
y

array([-0.57892113, -0.45101573, -0.32359977, -2.06307385,  0.68046968,
        0.8968824 , -0.27718042, -0.54095783, -0.73155561,  0.49379289])

In [128]:
np.maximum(x,y)

array([ 2.34683007,  0.45577208, -0.32359977, -0.13223669,  1.5466289 ,
        0.8968824 , -0.27718042, -0.36484072, -0.30743934,  1.14949153])

In [130]:
r,w=np.modf(np.sqrt(arr))

In [131]:
r

array([[0.        , 0.        , 0.41421356, 0.73205081],
       [0.        , 0.23606798, 0.44948974, 0.64575131],
       [0.82842712, 0.        , 0.16227766, 0.31662479],
       [0.46410162, 0.60555128, 0.74165739, 0.87298335],
       [0.        , 0.12310563, 0.24264069, 0.35889894],
       [0.47213595, 0.58257569, 0.69041576, 0.79583152],
       [0.89897949, 0.        , 0.09901951, 0.19615242],
       [0.29150262, 0.38516481, 0.47722558, 0.56776436]])

In [132]:
w

array([[0., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 3., 3., 3.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [135]:
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)

In [136]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [137]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [138]:
z=np.sqrt(xs**2+ys**2)

In [139]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [142]:
x=np.array([1.1,2.2,3.3,4.4])
y=np.array([2.1,3.2,4.3,5.4])
c=np.array([True,False,True,False])

In [144]:
r=[(x if c else y)for x,y,c in zip(x,y,c)]

In [145]:
r

[1.1, 3.2, 3.3, 5.4]

In [149]:
np.where(c,x,y)

array([1.1, 3.2, 3.3, 5.4])

In [2]:
arr=np.random.randn(5,4)
arr

array([[ 0.55265359, -1.23592029,  0.19076751,  0.0373246 ],
       [ 0.66587783, -1.38002187,  0.04693387, -0.5742336 ],
       [ 1.21762739,  0.7149286 ,  1.30252876, -0.44037613],
       [-0.68866836, -0.25400352,  1.58928473, -0.57710452],
       [-0.42450853,  1.78189228, -0.36957515,  1.42416954]])

In [3]:
arr.mean()

0.17897883578514992

In [4]:
np.mean(arr)

0.17897883578514992

In [5]:
arr.sum()

3.5795767157029985

In [6]:
arr.mean(axis=1)

array([-0.11379365, -0.31036094,  0.69867715,  0.01737708,  0.60299453])

In [7]:
arr.mean(axis=0)

array([ 0.26459638, -0.07462496,  0.55198794, -0.02604402])

In [12]:
arr.cumsum()

array([ 0.55265359, -0.6832667 , -0.49249919, -0.45517458,  0.21070325,
       -1.16931862, -1.12238476, -1.69661836, -0.47899097,  0.23593762,
        1.53846638,  1.09809025,  0.40942189,  0.15541838,  1.7447031 ,
        1.16759858,  0.74309005,  2.52498233,  2.15540718,  3.57957672])

In [14]:
arr.cumsum(axis=0)

array([[ 0.55265359, -1.23592029,  0.19076751,  0.0373246 ],
       [ 1.21853142, -2.61594216,  0.23770138, -0.536909  ],
       [ 2.4361588 , -1.90101356,  1.54023014, -0.97728513],
       [ 1.74749045, -2.15501708,  3.12951486, -1.55438965],
       [ 1.32298192, -0.3731248 ,  2.75993971, -0.13022011]])

In [16]:
arr.cumprod(axis=1)

array([[ 0.55265359, -0.68303578, -0.13030104, -0.00486343],
       [ 0.66587783, -0.91892597, -0.04312875,  0.02476598],
       [ 1.21762739,  0.87051664,  1.13387295, -0.49933058],
       [-0.68866836,  0.17492419,  0.27800434, -0.16043756],
       [-0.42450853, -0.75642847,  0.27955716,  0.39813679]])

In [18]:
(arr>0).sum()

11

In [19]:
(arr>0).any()

True

In [20]:
(arr>0).all()

False

In [21]:
arr.sort()

In [22]:
arr

array([[-1.23592029,  0.0373246 ,  0.19076751,  0.55265359],
       [-1.38002187, -0.5742336 ,  0.04693387,  0.66587783],
       [-0.44037613,  0.7149286 ,  1.21762739,  1.30252876],
       [-0.68866836, -0.57710452, -0.25400352,  1.58928473],
       [-0.42450853, -0.36957515,  1.42416954,  1.78189228]])

In [23]:
arr.sort(0)

In [24]:
arr

array([[-1.38002187, -0.57710452, -0.25400352,  0.55265359],
       [-1.23592029, -0.5742336 ,  0.04693387,  0.66587783],
       [-0.68866836, -0.36957515,  0.19076751,  1.30252876],
       [-0.44037613,  0.0373246 ,  1.21762739,  1.58928473],
       [-0.42450853,  0.7149286 ,  1.42416954,  1.78189228]])

In [27]:
np.unique(names)

array(['alice', 'bob', 'joe'], dtype='<U5')

In [28]:
set(names)

{'alice', 'bob', 'joe'}

In [30]:
sorted(set(names))

['alice', 'bob', 'joe']

In [31]:
arr=np.array([1,2,4,1,3,5,6])

In [32]:
np.in1d(arr,[1,4,6])

array([ True, False,  True,  True, False, False,  True])

In [33]:
np.save('arr',arr)

In [35]:
np.load('arr.npy')

array([1, 2, 4, 1, 3, 5, 6])

In [36]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [37]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [38]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [39]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [40]:
x @ np.ones(3)

array([ 6., 15.])

In [41]:
from numpy.linalg import inv, qr

In [42]:
X = np.random.randn(5, 5)

In [43]:
mat = X.T.dot(X)

In [44]:
mat

array([[ 1.18685032,  0.22993405, -1.49816118,  1.54825371,  2.4248498 ],
       [ 0.22993405,  9.60228444, -1.10717804, -4.0277663 , -6.80516701],
       [-1.49816118, -1.10717804,  3.54786164, -1.27558396, -3.86761711],
       [ 1.54825371, -4.0277663 , -1.27558396,  4.25762165,  5.71765625],
       [ 2.4248498 , -6.80516701, -3.86761711,  5.71765625, 21.94938568]])

In [45]:
inv(mat)

array([[16.29880092, -4.08731937,  2.00257191, -8.53248864, -0.49231523],
       [-4.08731937,  1.3181381 , -0.24163242,  2.40376693,  0.19147829],
       [ 2.00257191, -0.24163242,  0.82971155, -0.77956678,  0.05312296],
       [-8.53248864,  2.40376693, -0.77956678,  5.06916181,  0.23004053],
       [-0.49231523,  0.19147829,  0.05312296,  0.23004053,  0.10875014]])

In [46]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  1.98219043e-16, -7.54441043e-17,
        -1.48261730e-15, -2.64354032e-16],
       [ 2.63638828e-15,  1.00000000e+00, -2.96853551e-16,
         1.99303068e-15,  2.04113098e-17],
       [ 1.88542532e-15, -1.91284013e-15,  1.00000000e+00,
        -6.33109691e-16, -1.36447044e-17],
       [ 1.29237893e-15,  2.47560930e-15, -1.79822369e-18,
         1.00000000e+00, -2.11745431e-16],
       [-3.58825630e-15,  4.84057912e-15,  1.67148249e-16,
         9.97463916e-16,  1.00000000e+00]])

In [47]:
q, r = qr(mat)

In [48]:
q

array([[-0.34285774, -0.18374836, -0.37290204,  0.10173111, -0.83622961],
       [-0.06642343, -0.88320678, -0.15289132,  0.29390124,  0.32523839],
       [ 0.43278934,  0.30439352, -0.58416974,  0.60880352,  0.09023282],
       [-0.44726008,  0.14409376, -0.65659822, -0.44203768,  0.39073888],
       [-0.70049147,  0.26974784,  0.25532881,  0.58071835,  0.18471923]])

In [49]:
r

array([[ -3.4616407 ,   5.37259435,   5.40242601,  -6.72478551,
        -19.98585636],
       [  0.        , -11.27612561,   1.10601289,   5.04040402,
         11.13220771],
       [  0.        ,   0.        ,  -1.49457607,  -0.55204329,
          4.24567217],
       [  0.        ,   0.        ,   0.        ,  -0.36452126,
          6.11100824],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.6985654 ]])

In [51]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 0.10274881,  1.00794635, -0.76901303,  0.05753411],
       [-0.35048024, -0.09872222,  0.03842965, -0.08336204],
       [-1.01838475, -1.7879392 , -0.30155695, -0.76062252],
       [-0.46894708,  1.28034489,  2.38143036,  0.62823353]])

In [52]:
from random import normalvariate

In [53]:
#随机数状态
rng = np.random.RandomState(1234)
rng

In [54]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [61]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step

In [68]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [72]:
walk.min()

-9

In [73]:
walk.max()

30

In [79]:
#返回第一个true的位置
(np.abs(walk)>10).argmax()

174

In [80]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[ -1,  -2,  -1, ...,  32,  31,  30],
       [ -1,   0,   1, ...,  10,   9,   8],
       [  1,   0,  -1, ...,  48,  49,  50],
       ...,
       [ -1,   0,   1, ...,   0,   1,   0],
       [ -1,  -2,  -3, ..., -34, -35, -36],
       [  1,   0,   1, ...,   2,   3,   4]], dtype=int32)

In [82]:
walks.max()

127

In [83]:
walks.min()

-124

In [85]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([ True, False,  True, ..., False,  True, False])

In [86]:
hits30.sum()

3399

In [87]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

501.77493380406

In [88]:
steps = np.random.normal(loc=0, scale=0.25,size=(nwalks, nsteps))

In [89]:
steps

array([[-0.07170826,  0.17734263, -0.03329387, ..., -0.04251294,
        -0.22145164,  0.39332788],
       [-0.36737486, -0.14512624, -0.34748411, ...,  0.04422089,
         0.0845326 , -0.08538306],
       [ 0.18862618,  0.32033803, -0.06449178, ..., -0.42651178,
         0.30568538,  0.31006196],
       ...,
       [-0.12884978,  0.1832531 , -0.23837916, ..., -0.31313349,
         0.39702377, -0.49143003],
       [ 0.16223686, -0.17728037,  0.26856524, ...,  0.16195626,
        -0.21194302, -0.33394832],
       [ 0.26768565,  0.08857918, -0.21346239, ..., -0.17845972,
         0.12927049,  0.01637518]])