## 处理缺失值

In [1]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0]=None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 过滤缺失值

In [8]:
from numpy import nan as NA

In [9]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
    [NA, NA, NA], [NA, 6.5, 3.]])
data.dropna(how='all',axis=0)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[0]

0    1.0
1    1.0
2    NaN
3    NaN
Name: 0, dtype: float64

In [14]:
df = pd.DataFrame(np.random.randn(7, 3))

In [18]:
df.iloc[:4,1]=NA

In [19]:
df

0         1         2
0  0.604945       NaN -0.568856
1 -1.346612       NaN  0.155911
2 -0.930974       NaN  0.118093
3 -0.909385       NaN  2.618243
4 -1.471070 -0.397867  0.262976
5 -0.629814  1.097197  0.446232
6 -0.486867  1.115121  0.863004

In [21]:
df.dropna(axis=0)

0         1         2
4 -1.471070 -0.397867  0.262976
5 -0.629814  1.097197  0.446232
6 -0.486867  1.115121  0.863004

In [22]:
df.dropna(thresh=2)

0         1         2
0  0.604945       NaN -0.568856
1 -1.346612       NaN  0.155911
2 -0.930974       NaN  0.118093
3 -0.909385       NaN  2.618243
4 -1.471070 -0.397867  0.262976
5 -0.629814  1.097197  0.446232
6 -0.486867  1.115121  0.863004

### 填充缺失值

In [23]:
df.fillna(0)

0         1         2
0  0.604945  0.000000 -0.568856
1 -1.346612  0.000000  0.155911
2 -0.930974  0.000000  0.118093
3 -0.909385  0.000000  2.618243
4 -1.471070 -0.397867  0.262976
5 -0.629814  1.097197  0.446232
6 -0.486867  1.115121  0.863004

In [24]:
df.fillna({1:0.5})

0         1         2
0  0.604945  0.500000 -0.568856
1 -1.346612  0.500000  0.155911
2 -0.930974  0.500000  0.118093
3 -0.909385  0.500000  2.618243
4 -1.471070 -0.397867  0.262976
5 -0.629814  1.097197  0.446232
6 -0.486867  1.115121  0.863004

In [35]:
df.iloc[2:,2]=NA

In [32]:
df.fillna(method='ffill')

0         1         2
0  0.604945       NaN -0.568856
1 -1.346612       NaN  0.155911
2 -0.930974       NaN  0.155911
3 -0.909385       NaN  0.155911
4 -1.471070 -0.397867  0.155911
5 -0.629814  1.097197  0.155911
6 -0.486867  1.115121  0.155911

In [37]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.604945       NaN -0.568856
1 -1.346612       NaN  0.155911
2 -0.930974       NaN  0.155911
3 -0.909385       NaN  0.155911
4 -1.471070 -0.397867       NaN
5 -0.629814  1.097197       NaN
6 -0.486867  1.115121       NaN

In [38]:
df.fillna(data.mean())

0         1         2
0  0.604945  6.500000 -0.568856
1 -1.346612  6.500000  0.155911
2 -0.930974  6.500000  3.000000
3 -0.909385  6.500000  3.000000
4 -1.471070 -0.397867  3.000000
5 -0.629814  1.097197  3.000000
6 -0.486867  1.115121  3.000000

## 数据转换

### 删除重复

In [41]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
    'k2': [1, 1, 2, 3, 3, 4, 4]})

In [42]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [43]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [44]:
data.drop_duplicates(['k1'])

k1  k2
0  one   1
1  two   1

### 使用函数或映射数据转换

In [2]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
    'Pastrami', 'corned beef', 'Bacon',
    'pastrami', 'honey ham', 'nova lox'],
    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [3]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [5]:
lowercased = data['food'].str.lower()

In [6]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [8]:
data['food'].map(meat_to_animal)

0       pig
1       pig
2       pig
3       NaN
4       cow
5       NaN
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 替代值

In [9]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [10]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [13]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [14]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 重命名轴索引

In [15]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
    index=['Ohio', 'Colorado', 'New York'],
    columns=['one', 'two', 'three', 'four'])

In [16]:
transform = lambda x: x[:4].upper()

In [22]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [23]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [24]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [26]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 离散和装箱

In [2]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [28]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [29]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [30]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [3]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [4]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [5]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [6]:
data = np.random.rand(20)
data

array([0.72961424, 0.14735426, 0.63502322, 0.28601104, 0.01777816,
       0.73624018, 0.03351298, 0.70708346, 0.23628154, 0.47466617,
       0.89041833, 0.4439739 , 0.68320207, 0.79304417, 0.85182612,
       0.54183753, 0.18078976, 0.58943735, 0.93311752, 0.26973526])

In [7]:
pd.cut(data, 4, precision=2)

[(0.7, 0.93], (0.017, 0.25], (0.48, 0.7], (0.25, 0.48], (0.017, 0.25], ..., (0.48, 0.7], (0.017, 0.25], (0.48, 0.7], (0.7, 0.93], (0.25, 0.48]]
Length: 20
Categories (4, interval[float64]): [(0.017, 0.25] < (0.25, 0.48] < (0.48, 0.7] < (0.7, 0.93]]

In [8]:
data = np.random.randn(1000)

In [9]:
cats = pd.qcut(data, 4)

In [10]:
cats

[(0.734, 3.38], (0.0121, 0.734], (0.734, 3.38], (-3.1799999999999997, -0.632], (0.734, 3.38], ..., (0.0121, 0.734], (-0.632, 0.0121], (-0.632, 0.0121], (-0.632, 0.0121], (-3.1799999999999997, -0.632]]
Length: 1000
Categories (4, interval[float64]): [(-3.1799999999999997, -0.632] < (-0.632, 0.0121] < (0.0121, 0.734] < (0.734, 3.38]]

In [11]:
pd.value_counts(cats)

(0.734, 3.38]                    250
(0.0121, 0.734]                  250
(-0.632, 0.0121]                 250
(-3.1799999999999997, -0.632]    250
dtype: int64

In [12]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0121, 1.362], (0.0121, 1.362], (0.0121, 1.362], (-1.248, 0.0121], (0.0121, 1.362], ..., (0.0121, 1.362], (-1.248, 0.0121], (-1.248, 0.0121], (-1.248, 0.0121], (-3.1799999999999997, -1.248]]
Length: 1000
Categories (4, interval[float64]): [(-3.1799999999999997, -1.248] < (-1.248, 0.0121] < (0.0121, 1.362] < (1.362, 3.38]]

### 异常值

In [15]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018630    -0.028147     0.007402    -0.004742
std       0.996595     1.028329     1.005337     0.993920
min      -3.159919    -3.223721    -3.157889    -2.819274
25%      -0.641529    -0.711436    -0.676902    -0.660599
50%       0.009133    -0.061983     0.024685    -0.016160
75%       0.686646     0.691274     0.663809     0.688696
max       3.550690     3.046345     3.521016     3.069526

In [16]:
col = data[2]
col[np.abs(col) > 3]

15    -3.157889
68     3.521016
510   -3.153774
524    3.421519
Name: 2, dtype: float64

In [21]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
15  -0.424870  0.879483 -3.157889 -0.152607
68   0.290121 -0.727559  3.521016  1.344579
510  0.456910 -0.914813 -3.153774 -1.222908
524  1.002189 -0.081124  3.421519 -0.152016
715 -3.159919 -0.073173 -0.260915 -0.081882
804  3.550690 -0.453313  1.551617 -0.753727
825 -2.247240 -3.223721 -0.024736 -2.030865
891  1.126872  3.046345  0.938594  0.823456
915  1.069922  0.563115 -0.231731  3.069526
978  3.101027  1.151838  1.886486  0.523961

In [22]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [27]:
(np.sign(data) * 3).head()

0    1    2    3
0  3.0  3.0 -3.0 -3.0
1 -3.0  3.0  3.0 -3.0
2 -3.0  3.0  3.0 -3.0
3 -3.0  3.0  3.0  3.0
4 -3.0 -3.0 -3.0  3.0

### 置换抽样

In [28]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [30]:
np.arange(5 * 4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
sampler = np.random.permutation(5)

In [32]:
sampler

array([1, 3, 0, 4, 2])

In [33]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [34]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

In [36]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
4  16  17  18  19

### 虚拟变量

In [37]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
    'data1': range(6)})

In [38]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [45]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [46]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [47]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy 

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

## 字符串

### 字符串对象方法

In [50]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [52]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [53]:
first, second, third = pieces

In [54]:
first

'a'

In [55]:
'::'.join(pieces)

'a::b::guido'

In [56]:
 'guido' in val

True

In [57]:
val.index(',')

1

In [61]:
val.find(':')

-1

In [62]:
val.count(',')

2

In [63]:
val.replace(',',':')

'a:b: guido'

### 正则

In [64]:
import re

In [65]:
text = "foo bar\tbaz  \tqux"

In [66]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [67]:
regex = re.compile('\s+')

In [68]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [69]:
regex.findall(text)

[' ', '\t', '  \t']

In [70]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern =r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [71]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [72]:
m = regex.search(text)

In [73]:
text[m.start():m.end()]

'dave@google.com'

In [74]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



### pandas中的字符串

In [75]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
    'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)

In [76]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [77]:
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'

In [80]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [dave@google.com]
Steve    [steve@gmail.com]
Rob        [rob@gmail.com]
Wes                    NaN
dtype: object

In [81]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [82]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [83]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

## 分层索引

In [84]:
data = pd.Series(np.random.randn(9),
    index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
    [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -0.785067
   2   -0.272531
   3   -1.218732
b  1    1.005098
   3    0.063305
c  1    0.254152
   2    0.851730
d  2    0.551915
   3    1.169439
dtype: float64

In [85]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [86]:
data['b']

1    1.005098
3    0.063305
dtype: float64

In [87]:
data['b':'c']

b  1    1.005098
   3    0.063305
c  1    0.254152
   2    0.851730
dtype: float64

In [88]:
data.loc[:, 2]

a   -0.272531
c    0.851730
d    0.551915
dtype: float64

In [90]:
data.unstack()

1         2         3
a -0.785067 -0.272531 -1.218732
b  1.005098       NaN  0.063305
c  0.254152  0.851730       NaN
d       NaN  0.551915  1.169439

In [91]:
data.unstack().stack()

a  1   -0.785067
   2   -0.272531
   3   -1.218732
b  1    1.005098
   3    0.063305
c  1    0.254152
   2    0.851730
d  2    0.551915
   3    1.169439
dtype: float64

In [92]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
    columns=[['Ohio', 'Ohio', 'Colorado'],
    ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [93]:
frame.index.names = ['key1', 'key2']

In [94]:
frame.columns.names = ['state', 'color']

In [95]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [96]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### 排序

In [100]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [101]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [102]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

### 统计

In [103]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [104]:
frame.sum(level='color', axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [105]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
    'c': ['one', 'one', 'one', 'two', 'two',
    'two', 'two'],
    'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [108]:
frame2=frame.set_index(['c', 'd'])

In [107]:
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [109]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## 合并数据集

In [110]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
    'data2': range(3)})

In [111]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [112]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [113]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [114]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [115]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
    'data1': range(7)})

In [116]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
    'data2': range(3)})

In [117]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [118]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [119]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [120]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [121]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
    'data1': range(6)})

In [122]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
    'data2': range(5)})

In [123]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [124]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [125]:
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [126]:
pd.merge(df1, df2, how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [127]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
    'key2': ['one', 'two', 'one'],
    'lval': [1, 2, 3]})

In [128]:
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
    'key2': ['one', 'one', 'one', 'two'],
    'rval': [4, 5, 6, 7]})

In [129]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [130]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [131]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [132]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [133]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

### 索引合并

In [134]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
    'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [135]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [136]:
right1

group_val
a        3.5
b        7.0

In [137]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [141]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

### 轴向连接

In [142]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [145]:
s1 = pd.Series([0, 1], index=['a', 'b'])

In [146]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])

In [147]:
s3 = pd.Series([5, 6], index=['f', 'g'])

In [148]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [149]:
pd.concat([s1, s2, s3], axis=1)

D:\anzhuanggongju\Anaconda3-5.2.0\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [151]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [152]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [153]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

D:\anzhuanggongju\Anaconda3-5.2.0\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [154]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
    columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
    columns=['three', 'four'])

In [155]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

D:\anzhuanggongju\Anaconda3-5.2.0\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [156]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],
     names=['upper', 'lower'])

D:\anzhuanggongju\Anaconda3-5.2.0\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  


upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [157]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [158]:
pd.concat([df1, df2], ignore_index=True)

D:\anzhuanggongju\Anaconda3-5.2.0\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


a         b         c         d
0  0.403177  0.990368  0.308067 -0.409458
1  1.114726  1.045876 -1.276298  0.389048
2 -0.452887  0.078004 -0.450144  0.422916
3  0.606420  2.615971       NaN  1.015413
4  0.747851 -1.064448       NaN -1.335434

### 联合重叠数据

In [159]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
    index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
    index=['f', 'e', 'd', 'c', 'b', 'a'])

In [160]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [161]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [162]:
b[-1] = np.nan

In [163]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [167]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

## 重塑

In [168]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
    index=pd.Index(['Ohio', 'Colorado'], name='state'),
    columns=pd.Index(['one', 'two', 'three'],
    name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [169]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [170]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [171]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [172]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [173]:
df = pd.DataFrame({'left': result, 'right': result + 5},
    columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [174]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [175]:
df.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

In [176]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]})

In [177]:
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [178]:
melted = pd.melt(df, ['key'])

In [179]:
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [180]:
reshaped = melted.pivot('key', 'variable', 'value')

In [181]:
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [182]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [183]:
pd.melt(df, id_vars=['key'], value_vars=['A', 'B'])

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [184]:
pd.melt(df, value_vars=['A', 'B', 'C'])

variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [185]:
pd.melt(df, value_vars=['key', 'A', 'B'])

variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6